'use strict';
import { StyleSheet } from "react-native";

module.exports  = StyleSheet.create({
    icons:{
        width:15,
        height:15,
        margin:2,
    },
    iconsDestacable:{
        width:25,
        height:25,
        margin:2,
    },
    backgroundStyle:{
        backgroundColor:'white',
    },
    searchView:{
        padding:10,
        width:40,
    },
    searchInput:{   
        margin:10,
        backgroundColor:'white',
        borderWidth:1,
        borderColor:'black',
        borderRadius:100,
        alignItems:'center',
    },
    card:{
        margin:20,
        border:1,
        borderRadius:10,
        backgroundColor:'#f5fdff',
        flexDirection:'row',

    },
    cardImageContain:{
        flex:2,
        alignItems:'center'
    },
    cardInfo:{
        margin:10,
        flex:3,
    },
    cardImg:{
        width:120,
        height:115,
        margin:10,
        resizeMode:'cover',
        borderRadius:10,
    },
    points:{
        flexDirection:'row',
        width:75,
        backgroundColor:'#fbedb7',
        padding:5,
        borderRadius:100,
        color:'#7a6229',
        position:'absolute',
        marginTop:90,
        
        
    },
    cardTitle:{
        fontWeight:'bold',
        color:'black',
        fontSize:18,
    },
    textCard:{
        fontSize:14,
        marginLeft:5,
        marginRight:'auto',
    },
    flexDirectionRow:{
        marginVertical:5,
        flexDirection:'row',
    }
  });